DROP TABLE LIBROS;

CREATE TABLE LIBROS(
TITULO VARCHAR2(20),
AUTOR VARCHAR2(20),
EDITORIAL VARCHAR2(30)
);

DESCRIBE LIBROS;

INSERT INTO LIBROS (TITULO,AUTOR,EDITORIAL)
VALUES
('EL REY','Alexis','Picaso');

SELECT * FROM LIBROS;

INSERT ALL
    INTO LIBROS (TITULO, AUTOR, EDITORIAL) VALUES ('KING', 'Demos', 'Tep')
    INTO LIBROS (TITULO, AUTOR, EDITORIAL) VALUES ('QUEEN', 'Maria', 'Sunrise')
    INTO LIBROS (TITULO, AUTOR, EDITORIAL) VALUES ('PRINCE', 'Juan', 'Luna')
SELECT * FROM dual;

SELECT * FROM LIBROS;

SELECT * FROM dual;



